# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 01:40
from __future__ import unicode_literals

from django.db import migrations


def copy_src_to_dst(source, destination):
    for src in source.objects.all():
        dst = destination(
            title=src.title,
            start=src.start,
            description=src.description,
            slots=src.slots
        )
        dst.save()
        dst.speakers.set(src.speakers.all())
        src.delete()


def forward_abc_to_mti(apps, schema_editor):
    copy_src_to_dst(
        apps.get_model('core', 'CourseOld'),
        apps.get_model('core', 'Course')
    )


def backward_mti_to_abc(apps, schema_editor):
    copy_src_to_dst(
        apps.get_model('core', 'Course'),
        apps.get_model('core', 'CourseOld')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_course'),
    ]

    operations = [
        migrations.RunPython(forward_abc_to_mti, backward_mti_to_abc)
    ]
